### ISSUE TITLE
14 레퍼런스 가이드: [Objects > XComponents > WebBrowser > Event > onusernotify]

### ISSUE THREAD

**Issue by goodjob311** [TOBESOFT-DOCS/TOBESOFT-docs-issue#12]
Remark에서 "**3) Windows Runtime의 경우**"의 내용에서 틀린 부분이 없는지 확인 부탁 드립니다.

Windows Runtime이 라면 데스크탑 환경입니다.
그런데 기술된 스크립트 코드를 봤을 때, 그리고  Internet Explorer의 길이제약을 받는다는 설명이 HTML5 환경을 시사하는 것 아닌가 하는 의구심이 듭니다.

※ 제가 기술적인 부분을 명확히 이해하지 못한 것 같습니다. 그럼에도 불구하고 의문을 제기하는 건 넥사크로 17 레퍼런스 가이드와 비교했을 때 정보가 불일치하다고 느꼈기 때문입니다. 17에서 동일한 이벤트 (onusernotify)의 문서를 참고해 주시기 바랍니다.

**Comment by koko8829** [comment]
런타임 내부에서 WebBrowser 컴포넌트를 사용하는 경우 내부적으로 브라우저 모듈을 사용하는데 그 과정에서 해당 제약이 발생한다는 의미입니다.
사용하는 브라우저 모듈이 IE를 기준으로 동작하며 해당 동작을 Internet Explorer의 길이 제약을 받는다고 설명하고 있습니다.
