### ISSUE TITLE
14 레퍼런스 가이드: [Objects > Misc. Objects > ExcelExportObject]

### ISSUE THREAD

**Issue by goodjob311** [TOBESOFT-DOCS/TOBESOFT-docs-issue#13]
Remark 부분입니다. (2017년 11월 배포에 나갈 내용입니다.)

* string 타입의 경우 mask가 적용된 data를 _**수신함으로**_ 별도 mask 처리를 하지 않음.
→ string 타입의 경우 mask가 적용된 data를 _**수신하므로**_ 별도 mask 처리를 하지 않음. 

* nexacro의 '9 '는 excel에 적용되지 _**않음으로**_ #으로 변경.
→ nexacro의 '9 '는 excel에 적용되지 _**않으므로**_ #으로 변경.

**Comment by koko8829** [comment]
해당 오타 수정했습니다.
참고: [http://www.korean.go.kr/front/mcfaq/mcfaqView.do?mcfaq_seq=2603](http://www.korean.go.kr/front/mcfaq/mcfaqView.do?mcfaq_seq=2603)
