### ISSUE TITLE
14 레퍼런스 가이드: [Objects > XComponents > PopupMenu] 의 idcolumn, levelcolumn, captioncolumn 속성

### ISSUE THREAD

**Issue by goodjob311** [TOBESOFT-DOCS/TOBESOFT-docs-issue#14]
PopupMenu의 3가지 속성 idcolumn, levelcolumn, captioncolumn 입니다.
3개 문서 모두 Remark를 봐주시기 바랍니다.

"idcolumn, levelcolumn, cationcolumn 항목은 필수 항목입니다."는 문구가 공통으로 들어 있습니다.
여기에서 cationcolumn → captioncolumn으로 바꿔야 할 것 같습니다.

※ Menu 컴포넌트와 TrayPopupMenu 오브젝트도 확인해 주시기 바랍니다.
살펴보니 일부는 올바르게 쓰여 있지만 다른 일부는 틀린 상태입니다.

**Comment by koko8829** [comment]
아래 항목 수정했습니다.
Objects > Appication Objects > Tray > TrayPopupMenu > Property > captioncolumn
Objects > Appication Objects > Tray > TrayPopupMenu > Property > innerdataset
Objects > Appication Objects > Tray > TrayPopupMenu > Property > levelcolumn
Objects > XComponents > Menu > Property > levelcolumn
Objects > XComponents > PopupMenu > Property > captioncolumn
Objects > XComponents > PopupMenu > Property > idcolumn
Objects > XComponents > PopupMenu > Property > levelcolumn
