### ISSUE TITLE
fastvscrolltype 속성 관련 가이드 요청

### ISSUE THREAD

**Issue by TOBESOFT-DOCS** [TOBESOFT-DOCS/TOBESOFT-docs-issue#15]
새로 추가된 fastvscrolltype 속성에 관한 예제를 올려주셨으면 합니다.

**Comment by koko8829** [comment]
개발 가이드에 "Smart Scroll 기능 사용하기" 항목 추가했습니다.
[http://docs.tobesoft.com/developer_guide_nexacro_17_ko#cfeda121be925f84](http://docs.tobesoft.com/developer_guide_nexacro_17_ko#cfeda121be925f84)
