### ISSUE TITLE
개발 가이드 예제 화면에서 스크립트 내 주석 텍스트가 깨져 보입니다

### ISSUE THREAD

**Issue by TOBESOFT-DOCS** [TOBESOFT-DOCS/TOBESOFT-docs-issue#2]
Grid 컴포넌트 예제 중 스크립트 코드 내 주석 텍스트가 깨져있는 항목이 있습니다.
http://demo.nexacro.com/developer_guide/17/guide.html?sa=sample_grid_30&ma=2e314460f5a5869d

![image](https://user-images.githubusercontent.com/32917911/31802185-a8e600fe-b587-11e7-89c5-421085a86fe8.png)

**Comment by TOBESOFT-DOCS** [comment]
참고로 윈도우 10 영문 로케일 설정에서 확인했습니다.

**Comment by donudory** [comment]
파일에서 문자를 읽어들일 때 바이트 단위로 읽어 들여서 2바이트 문자의 경우 깨지는 문제가 있었습니다.
viewsource.jsp 수정하여 demo 서버에 반영 후 테스트 완료했습니다.
