### ISSUE TITLE
14 레퍼런스 가이드: [Objects > DeviceAPI > FileDialog > Method > open]

### ISSUE THREAD

**Issue by goodjob311** [TOBESOFT-DOCS/TOBESOFT-docs-issue#25]
Return value에 대한 설명을 보면 "잘못된 Paramter 값을 설정하는 경우에만 false값을 리턴" 이라는 문구가 있습니다.
Paramter 를 Parameter로 바꾸어야 할 것 같습니다.

**Comment by koko8829** [comment]
수정완료
