### ISSUE TITLE
14 레퍼런스 가이드: [Objects > DeviceAPI > FileDialog > Method > open]

### ISSUE THREAD

**Issue by goodjob311** [TOBESOFT-DOCS/TOBESOFT-docs-issue#26]
Parameters 표에서 strFileName 파라미터에 대한 설명을 봐주시기 바랍니다.
"enumOpenMode가 FileDialog.SELFOLDER 이면 이 파라미터는 무시됩니다."라는 문구가 있습니다.
enumOpenMode라 지칭하였는데 constOpenMode가 맞지 않나요?
Parameters 표를 보면 constOpenMode라 나와 있습니다.

확인 부탁 드립니다.

**Comment by koko8829** [comment]
담당자 문의중입니다.

**Comment by koko8829** [comment]
수정됐습니다.
