### ISSUE TITLE
14 레퍼런스 가이드: [Objects > XComponents > ProgressBar > Property > barcolor]

### ISSUE THREAD

**Issue by goodjob311** [TOBESOFT-DOCS/TOBESOFT-docs-issue#28]
Remark 란을 보시면 
"그러데이션을 지정하려면 속성값을 @gradation 으로 지정하고 bargradtaiton 속성을 적용합니다."
라는 문장이 있습니다.

bargradtaiton을 → bargradation 으로 바꾸어야 할 것 같습니다.

**Comment by koko8829** [comment]
수정됐습니다.
