### ISSUE TITLE
14 레퍼런스 가이드: [Objects > XComponents > WebBrowser > Event > onusernotify]

### ISSUE THREAD

**Issue by goodjob311** [TOBESOFT-DOCS/TOBESOFT-docs-issue#3]
Remark 부분을 봐주시기 바랍니다.

"Window Runtime" 로 두 번 표기되어 있는데 "Windows Runtime" 로 고쳐야 할 것 같습니다.

감사합니다.

**Comment by koko8829** [comment]
오타 수정했습니다.
10월 정기 배포에 반영할 예정입니다.
