### ISSUE TITLE
14 레퍼런스 가이드: [Objects > Misc. Objects > System > Method > requestDevicePermission]

### ISSUE THREAD

**Issue by goodjob311** [TOBESOFT-DOCS/TOBESOFT-docs-issue#31]
1. Description 을 보시면 "확안" 이라는 오타가 있습니다. "확인"으로 고쳐야 합니다.

2.  Parameters 표에서 "description" 파라미터 입니다.
설명에서 "다이어로그"로 쓰여있는데 문제 없나요? "다이얼로그"가 표준어 아닌가요?

**Comment by koko8829** [comment]
수정 완료
