### ISSUE TITLE
개발 가이드 > 20.7Grid간의 복사/붙여넣기 에서 TexaArea에 복사한 값을 저장하는 이유는 무엇인가요?

### ISSUE THREAD

**Issue by TOBESOFT-DOCS** [TOBESOFT-DOCS/TOBESOFT-docs-issue#4]
개발 가이드 > 20.7Grid간의 복사/붙여넣기 에서 TexaArea에 복사한 값을 저장하는 이유는 무엇인가요?

```
//copy from selected row to textarea 
this.TextArea00.value = "";
this.TextArea00.set_value(sClip.substr(0, sClip.length-1));
```

**Comment by donudory** [comment]
원래는 임시 저장 공간으로의 용도와 사용자가 선택, 복사한 내용을 화면상에서 보여주기 위한 용도였습니다. 그러나 후에 큰 의미가 없는거 같아 TextArea를 화면에서 제거했는데 그러면서 코드를 수정하지 않아 그대로 남아 있는 것입니다. 임시 저장 공간으로의 용도만이라면 일반 변수를 사용해도 무방합니다.

**Comment by donudory** [comment]
샘플과 설명을 수정했습니다.
