### ISSUE TITLE
14 레퍼런스 가이드: [Objects > Frame Objects > FrameSet > Property > tabkeycirculation]

### ISSUE THREAD

**Issue by goodjob311** [TOBESOFT-DOCS/TOBESOFT-docs-issue#48]
Setting Syntax 표를 봐주시기 바랍니다.

1. _all,no_minimize_ 값에 대한 설명을 보시면 "minized된" 이라고 쓰여 있습니다. "minimized된" 으로 수정되어야 합니다.

2. _active_only_ 값에 대한 설명을 보시면 "activate창만" 이라는 표현이 있습니다. "activated된 창으로만" 이 더 정확한 표현 아닐까요?

**Comment by koko8829** [comment]
내용 수정 완료
