### ISSUE TITLE
14 레퍼런스 가이드: [Objects > EventInfo Objects > AudioEventInfo > Property > reason]

### ISSUE THREAD

**Issue by goodjob311** [TOBESOFT-DOCS/TOBESOFT-docs-issue#5]
하단의 표를 봐주시기 바랍니다. 이벤트 발생 원인을 기술한 표입니다.
표에서 AudioRecording > REASON_RECORDING_START 입니다.

Description에 보면 "RrecordingStart가 호출되어"라는 문구가 나옵니다.
"RrecordingStart"의 철자가 맞는 것인지 아니면 어두에 있는 "Rr"이 오타인지 확신이 안 섭니다.

확인 바랍니다.

**Comment by koko8829** [comment]
해당 항목은 recordingStart 메소드의 오타입니다.
수정 후 10월 배포에 반영하겠습니다.
