### ISSUE TITLE
14 레퍼런스 가이드: [Objects > EventInfo Objects > AudioEventInfo > Property > reason]

### ISSUE THREAD

**Issue by goodjob311** [TOBESOFT-DOCS/TOBESOFT-docs-issue#6]
하단의 표를 봐주시기 바랍니다. 이벤트 발생 원인을 기술한 표입니다.
표에서 AudioRecording > REASON_RECORDING 입니다.

Description에 "지정된 간격으로 recording 이벤트를 발생" 이라는 설명이 있습니다.
"recording 이벤트" 가 맞는 말인가요? 혹시 "onrecording" 이벤트의 잘못 아닌가요?

그런 생각을 하는 이유는 AudioPlayer > REASON_PLAYING 에서는 "onplaying 이벤트"를 언급했기 때문입니다.

한 번 검토해주시기 바랍니다.

**Comment by koko8829** [comment]
해당 항목 수정했습니다.
10월 이후 배포에 반영될 예정입니다.
