### ISSUE TITLE
14 레퍼런스 가이드: [Platforms > Runtime > Plugins > NexacroLauncherAX > Property > key]

### ISSUE THREAD

**Issue by goodjob311** [TOBESOFT-DOCS/TOBESOFT-docs-issue#64]
14 레퍼런스 가이드 [Platforms > Runtime > Plugins > NexacroLauncherAX > Property > key] 에서 내용오류를 확인해보고 싶습니다.
Remark에 보면 "nexacro.xml 파일은 사용자 별 엑스플랫폼 애플리케이션 실행에 필요한 정보를 담는 XML 파일입니다." 는 문장이 있습니다.
그런데 "엑스플랫폼 애플리케이션" 맞는 건가요? 혹시 넥사크로 플랫폼 애플리케이션 아닌가요?
확인 바랍니다.

**Comment by koko8829** [comment]
해당 내용 수정 완료
