### ISSUE TITLE
14 레퍼런스 가이드: [Objects > XComponents > Grid > Method > autoSizeCol]

### ISSUE THREAD

**Issue by goodjob311** [TOBESOFT-DOCS/TOBESOFT-docs-issue#71]
* Parameter를 설명하는 표에서 nPivotIndex 파라미터입니다.
Description에서 "생략시 autosizingbandtype에 따라 처리됩니다."라는 문장입니다.
autosizebandtype이라는 속성은 있지만 autosizingbandtype이라는 속성은 없습니다.
확인 부탁 드립니다.

* Parameter를 설명하는 표에서 bBandIndex 파라미터 입니다.
Description에서 false 값을 설명하는 부분입니다.
"foramt" 을 format으로 고쳐야 합니다.

**Comment by koko8829** [comment]
수정 완료
