### ISSUE TITLE
14 레퍼런스 가이드: [Objects > XComponents > Radio > Property > innerdataset]

### ISSUE THREAD

**Issue by goodjob311** [TOBESOFT-DOCS/TOBESOFT-docs-issue#73]
Remark에서 아래 설명입니다.

"innerdataset, idcolumn, levelcolumn, captioncolumn 속성을 모두 설정해야 메뉴 아이템이 정상적으로 표시됩니다."

레퍼런스 가이드에서 Radio 컴포넌트의 idcolumn, levelcolumn과 captioncolumn 속성이 검색되지 않습니다.
그럼에도 불구하고 위 문장이 참인지 확인 부탁드립니다.

**Comment by koko8829** [comment]
수정 완료
