### ISSUE TITLE
Fit to contents 기능을 활용한 예제를 올려주세요

### ISSUE THREAD

**Issue by TOBESOFT-DOCS** [TOBESOFT-DOCS/TOBESOFT-docs-issue#9]
세미나 영상을 보면 다국어 처리를 Fit to contents 기능을 사용해 처리하고 있던데,
개발 가이드 문서에 Fit to contents 기능을 활용한 예제를 올려주셨으면 합니다.

**Comment by koko8829** [comment]
개발가이드 17.0.0.100.10 에 반영했습니다.
[Static > 글자 길이에 맞추어 배치하기]를 참고하세요.
